version: '3.1'

services:  
  database-postgres:
    container_name: database-postgres
    image: postgres:alpine
    ports:   
      - 5432:5432
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD} 
    networks:
      - odonts-network-api
    
  odonts-api:
    build: 
      context: .
      dockerfile: .docker/Dockerfile
    container_name: odonts-api
    ports:
      - 3000:3000
    volumes:
      - .:/app
    networks:
      - odonts-network-api
    depends_on:
      - database-postgres
    links:
      - database-postgres
    env_file:
      - .env

networks:
  odonts-network-api:
    name: donts-network