version: '3.5'

services:  
  database-postgres:
    container_name: aponta-database
    build:
      context: ../
      dockerfile: .docker/postgresql/Dockerfile
    ports:   
      - "${POSTGRES_PORT}:5432"
    environment:
      TZ: "America/Sao_Paulo"
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
    networks:
      - aponta-network-api
    restart: on-failure
    tty: true
    
  aponta-api:
    container_name: aponta-api
    build: 
      context: ../
      dockerfile: .docker/node/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    restart: on-failure
    environment:
      NODE_OPTIONS: ${NODE_OPTIONS}
    env_file:
      - ../.env
    ports:
      - "${API_PORT}:3000"
      - "${PRISMA_STUDIO}:5555"
    working_dir: /var/www/aponta-api
    volumes:
      - ../:/var/www/aponta-api
    networks:
      - aponta-network-api
    depends_on:
      - database-postgres
    links:
      - database-postgres
    tty: true

networks:
  aponta-network-api:
    name: aponta-network